variables:
  UV_VERSION: 0.6
  PYTHON_VERSION: 3.9
  # GitLab CI creates a separate mountpoint for the build directory,
  # so we need to copy instead of using hard links.
  UV_LINK_MODE: copy

.job-template:
  image: ghcr.io/astral-sh/uv:${UV_VERSION}-python${PYTHON_VERSION}-alpine
  variables:
    UV_CACHE_DIR: .uv-cache
  cache:
    key:
      files:
        - uv.lock
    paths:
      - $UV_CACHE_DIR
  before_script:
    - uv sync --frozen
    - uv cache prune --ci
  
stages:
  - test

test:
  extends: .job-template
  script:
    # - uv run --group test ruff format --diff
    - uv run --group test ruff check
    - uv run --group test pytest tests/

build:
  extends: .job-template
  script:
    - uv build
  artifacts:
    paths:
      - build/*
  rules:
    - if: $CI_COMMIT_TAG
      when: always

# pages:
#   script:
#     - pip install sphinx sphinx-rtd-theme
#     - cd docs
#     - make html
#     - mv build/html/ ../public/
#   artifacts:
#     paths:
#       - public
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# deploy:
#   stage: deploy
#   script: echo "Define your deployment script!"
#   environment: production
