name: Test and build with uv

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install the project
        run: uv sync --locked --all-extras

      - name: prune cache
        run: uv cache prune --ci

      - name: Run lynter
        run: uv run --group test ruff check

      - name: Run tests
        # For example, using `pytest`
        run: uv run --group test pytest tests/

      - name: Build
        run: uv build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists-${{ matrix.python-version }}
          path: dist/
