name: Publish

on:
  push:
    tags: ['v*.*.*']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          prune-cache: false
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - run: uv sync
      - run: echo "GNMIPY_VERSION=$(uvx dunamai from any --no-metadata --style pep440)" >> $GITHUB_ENV
      - run: uv build
      - uses: actions/upload-artifact@v7
        with:
          name: dist-${{ matrix.python-version }}-${{ env.GNMIPY_VERSION }}
          path: |
            dist/*.whl
            dist/*.tar.gz

  # create-release:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/download-artifact@v4
  #     - uses: actions/create-release@v1
  #       id: create_release
  #       with:
  #         draft: true
  #         prerelease: false
  #         release_name: release-${{ github.ref }}
  #         tag_name: ${{ github.ref }}
  #       env:
  #         GITHUB_TOKEN: ${{ github.token }}